[package]
name = "rust-points"
version = "0.1.0"
authors = ["Thomas J. Kennedy"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
lazy_static = "1.4.0"

[dev-dependencies]
hamcrest2 = "*"

