[package]
name = "enroll_students"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hamcrest2 = "0.3.0"
rstest = "0.24.0"
thiserror = "2.0.10"
